### PR TITLE
Added Brotato

### PR DESCRIPTION
**Pull request by SheldonCoulson99**
# Description

## Type(s) 

- [x] Game page addition

## Verification 
Have you

- [x] Followed the [contribution guidelines?](https://github.com/Whisky-App/whisky-book?tab=readme-ov-file#please-read-all-steps-before-contributing)
- [x] Ran `./scripts/generate.mjs`?
- [x] Ran `./scripts/lint.mjs`?
- [x] Checked spelling and grammar?
- [x] (If applicable) Provided documentation for a game not working? (i.e. detailing what happens when the game doesn't work?)
    - Brotato cannot be launched. When attempting to open the game, nothing happens — no errors, logs, or feedback.
    - Tested on `Version 2.3.4 (42)`

- [x] (If applicable) Ensured the linked Steam ID is the correct one for your game addition?

### CODE REVIEW

**Comment by mattmaniak** [comment]
Everything is ok apart of the Whisky version. Please test it with the freshest 2.3.4 as we require new contributions to be made with the latest Whisky version used. More info in Readme. Thanks.

**Comment by SheldonCoulson99** [comment]
> Everything is ok apart of the Whisky version. Please test it with the freshest 2.3.4 as we require new contributions to be made with the latest Whisky version used. More info in Readme. Thanks.

Okay, I tested it earlier today with the latest version and it still doesn't work. Thanks for reminding me to update. :)

**Comment by mattmaniak** [comment]
Thank you for the confirmation 🙂

**Review by mattmaniak — APPROVED** [review]
Check with Whisky 2.3.4.

**Pull request merged**
