### PR TITLE
Precise contributing docs, especially "opens" flag requirements; add 9 games; fix typos

### PR DESCRIPTION
**Pull request by mattmaniak**
Duplicate of #59 as the original PR has been force reset on my local repo accidentally. Deus Ex: Human Revolution is already merged #71. Fixed typos/added more formatting consistency in already added games.

### CODE REVIEW

**Comment by mattmaniak** [comment]
Added also:
- Sniper: Ghost Warrior 3;
- Sherlock Holmes: The Devil's Daughter;
- Sherlock Holmes Chapter One.

**Comment by mattmaniak** [comment]
Sniper Ghost Warrior Contracts has been added.

**Comment by JoshuaBrest** [comment]
Can you split this commit up? It's not fun to review big commits.

**Comment by mattmaniak** [comment]
Sure, will do.

**Comment by mattmaniak** [comment]
@JoshuaBrest made #95 for adding games only. I will keep this PR for comparison purposes before I split it to unique PRs.

**Review by hahayupgit — APPROVED** [review]

**Pull request merged**
