### PR TITLE
Fix GTA SA and Genshin Impact links

### PR DESCRIPTION
**Pull request by mattmaniak**
Fix links that are wrongly formatted (Genshin) and broken (GTA SA Steam). I approved and merged those PRs with those issues. I missed them basically.

### CODE REVIEW

**Comment by JoshuaBrest** [comment]
Genshi should also have a note with a ban disclaimer.

**Comment by mattmaniak** [comment]
@JoshuaBrest This ban disclaimer should be regarding what?

**Comment by JoshuaBrest** [comment]
> @JoshuaBrest This ban disclaimer should be regarding what? I mean in which point this Genshin setup may be risky. I didn't play the game so that is why I am asking.

Genshin Impact. In the past, they have had ban waves that affected Whisky users.

**Comment by mattmaniak** [comment]
> > @JoshuaBrest This ban disclaimer should be regarding what? I mean in which point this Genshin setup may be risky. I didn't play the game so that is why I am asking.
> 
> 
> 
> Genshin Impact. In the past, they have had ban waves that affected Whisky users.

Is there any link to such issue? Just to document it there.

**Comment by JoshuaBrest** [comment]
> > > @JoshuaBrest This ban disclaimer should be regarding what? I mean in which point this Genshin setup may be risky. I didn't play the game so that is why I am asking.
> > 
> > 
> > Genshin Impact. In the past, they have had ban waves that affected Whisky users.
> 
> Is there any link to such issue? Just to document it there.

https://discord.com/channels/1115955071549702235/1232559655113457694/1232559655113457694

**Review by hahayupgit — APPROVED** [review]
LGTM, I will add the Genshin warning in a separate PR

**Pull request merged**
