### PR TITLE
Add The Binding of Isaac: Repentance

### PR DESCRIPTION
**Pull request by SheldonCoulson99**
Add The Binding of Isaac: Repentance as fully playable.
Tested on `Version 2.3.2 (40)`

### CODE REVIEW

**Review by mattmaniak — CHANGES_REQUESTED** [review]
An alias looks the same as the title. Did you mean an alias without ":" in it?

**Comment by SheldonCoulson99** [comment]
> An alias looks the same as the title. Did you mean an alias withou ":" in it?

Ah, yes. I've changed it now in a new commit.

**Review by mattmaniak — APPROVED** [review]
Looks ok now.

**Comment by hahayupgit** [comment]
@SheldonCoulson99 can you please confirm that Repentance only works by launching `isaac-ng.exe` directly? I don't own Repentance personally but I own TBOI: Rebirth, and the game launches directly through Steam in Whisky, and as far as I can tell Repentance is just a DLC for Rebirth.

**Comment by SheldonCoulson99** [comment]
> @SheldonCoulson99 can you please confirm that Repentance only works by launching `isaac-ng.exe` directly? I don't own Repentance personally but I own TBOI: Rebirth, and the game launches directly through Steam in Whisky, and as far as I can tell Repentance is just a DLC for Rebirth.
> 
> 
> 
> If so, just let me know. Otherwise, looks good & is ready to merge.

Yes, both via steam in whisky and directly launching isaac-ng.exe works.
I just thought that since launching isaac-ng.exe will also launch steam. So I guess this way can make the player's life easier. 😄

**Comment by hahayupgit** [comment]
Ahh I see! Thank you for letting me know. I'm going to remove that portion of the documentation, since it launches through Steam, as we detail how to pin programs at a different place in the docs. But thank you so much for your additions! We greatly appreciate it.

**Review by hahayupgit — APPROVED** [review]

**Pull request merged**
