### PR TITLE
Added the game "Half Sword"

### PR DESCRIPTION
**Pull request by plyght**
Added Half Sword to Whisky Docs.

### CODE REVIEW

**Comment by JoshuaBrest** [comment]
@plyght Please fix all lint issues. (aliases require a space).

**Comment by hahayupgit** [comment]
@plyght that's my bad, the code should be `
`. I forgot the space when helping you in Discord.

**Comment by plyght** [comment]
> @plyght Please fix all lint issues. (aliases require a space).

Will do. Had some troubles with aliases as they're not present in the whisky-book tutorial for adding games.

**Comment by plyght** [comment]
> @plyght that's my bad, the code should be
> 
>  `<!-- script:Aliases [] -->`. I forgot the space when helping you in Discord.

No worries. Thanks for letting me know.

**Comment by plyght** [comment]
> @plyght Please fix all lint issues. (aliases require a space).

@JoshuaBrest Fixed all lint issues. should I make a new PR?

**Review by devium335 — APPROVED** [review]

**Review by IsaacMarovitz — APPROVED** [review]

**Pull request merged**
