### PR TITLE
Adds a few titles to compatibility list

### PR DESCRIPTION
**Pull request by joshandersn**
Adds a few games I tried yesterday. Is this the proper way to contribute to this project?

### CODE REVIEW

**Comment by hahayupgit** [comment]
Yes this is! Make sure to add your games to /src/game-support/README.md, however

**Comment by joshandersn** [comment]
Sure thing! I'll do that now.

**Comment by joshandersn** [comment]
done

**Comment by JoshuaBrest** [comment]
Please make sure to run it through a spell checker. I've noticed unnecessary capitalization and missing punctuation.

**Comment by joshandersn** [comment]
Gotcha will do

**Review by hahayupgit — APPROVED** [review]
Looks good to me

**Review by IsaacMarovitz — APPROVED** [review]

**Pull request merged**
